#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : boinc-client
Version  : 7.14.2
Release  : 2
URL      : https://github.com/BOINC/boinc/archive/client_release/7.14/7.14.2.tar.gz
Source0  : https://github.com/BOINC/boinc/archive/client_release/7.14/7.14.2.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0 LGPL-2.1 LGPL-3.0 MIT NCSA OFL-1.1
Requires: boinc-client-bin = %{version}-%{release}
Requires: boinc-client-lib = %{version}-%{release}
Requires: boinc-client-license = %{version}-%{release}
Requires: boinc-client-locales = %{version}-%{release}
Requires: boinc-client-services = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : docbook2X
BuildRequires : freeglut-dev
BuildRequires : gettext-bin
BuildRequires : gfortran
BuildRequires : libXScrnSaver-dev
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : mesa-dev
BuildRequires : nghttp2-dev
BuildRequires : openssl-dev
BuildRequires : pkg-config-dev
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libnotify)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-atom)
BuildRequires : pkgconfig(xmu)
BuildRequires : sqlite-autoconf-dev
BuildRequires : wxWidgets
BuildRequires : wxWidgets-dev
Patch1: 0001-Fixup-for-newer-wxWidgets.patch

%description
Stripchart version 2.0
----------------------
Author: Matt Lebofsky
BOINC/SETI@home - University of California, Berkeley
mattl@ssl.berkeley.edu

Date of recent version: November 4, 2002

%package bin
Summary: bin components for the boinc-client package.
Group: Binaries
Requires: boinc-client-license = %{version}-%{release}
Requires: boinc-client-services = %{version}-%{release}

%description bin
bin components for the boinc-client package.


%package dev
Summary: dev components for the boinc-client package.
Group: Development
Requires: boinc-client-lib = %{version}-%{release}
Requires: boinc-client-bin = %{version}-%{release}
Provides: boinc-client-devel = %{version}-%{release}

%description dev
dev components for the boinc-client package.


%package lib
Summary: lib components for the boinc-client package.
Group: Libraries
Requires: boinc-client-license = %{version}-%{release}

%description lib
lib components for the boinc-client package.


%package license
Summary: license components for the boinc-client package.
Group: Default

%description license
license components for the boinc-client package.


%package locales
Summary: locales components for the boinc-client package.
Group: Default

%description locales
locales components for the boinc-client package.


%package services
Summary: services components for the boinc-client package.
Group: Systemd services

%description services
services components for the boinc-client package.


%prep
%setup -q -n boinc-client_release-7.14-7.14.2
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1550271660
%reconfigure --disable-static --disable-silent-rules \
--enable-dynamic-client-linkage \
--disable-server \
--disable-fcgi \
--enable-unicode \
--with-ssl \
--with-x
make  %{?_smp_mflags} CXXFLAGS+="-DwxNB_FLAT=0x0800 -DwxADJUST_MINSIZE=0x0000"

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1550271660
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/boinc-client
cp COPYING %{buildroot}/usr/share/package-licenses/boinc-client/COPYING
cp COPYING.LESSER %{buildroot}/usr/share/package-licenses/boinc-client/COPYING.LESSER
cp api/ttf/liberation-fonts-ttf-2.00.0/LICENSE %{buildroot}/usr/share/package-licenses/boinc-client/api_ttf_liberation-fonts-ttf-2.00.0_LICENSE
cp drupal/sites/all/libraries/phpmailer/LICENSE %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_all_libraries_phpmailer_LICENSE
cp drupal/sites/all/libraries/tinymce/jscripts/tiny_mce/license.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_all_libraries_tinymce_jscripts_tiny_mce_license.txt
cp drupal/sites/all/themes/zen/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_all_themes_zen_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/bbcode/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_bbcode_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/cck/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_cck_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/content_profile/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_content_profile_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/elysia_cron/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_elysia_cron_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/features/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_features_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/filefield/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_filefield_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/flag/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_flag_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/forum_access/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_forum_access_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/htmlpurifier/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_htmlpurifier_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/i18nviews/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_i18nviews_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/jump/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_jump_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/panels/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_panels_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/privatemsg/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_privatemsg_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/views/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_views_LICENSE.txt
cp drupal/sites/default/boinc/modules/contrib/wysiwyg/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_wysiwyg_LICENSE.txt
cp drupal/sites/default/boinc/modules/node_comment_block/LICENSE.txt %{buildroot}/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_node_comment_block_LICENSE.txt
cp html/inc/random_compat/LICENSE %{buildroot}/usr/share/package-licenses/boinc-client/html_inc_random_compat_LICENSE
cp samples/wrappture/license.terms %{buildroot}/usr/share/package-licenses/boinc-client/samples_wrappture_license.terms
%make_install
%find_lang BOINC-Client
%find_lang BOINC-Manager

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/boinc
/usr/bin/boinc_client
/usr/bin/boinccmd
/usr/bin/boincmgr
/usr/bin/boincscr
/usr/bin/switcher

%files dev
%defattr(-,root,root,-)
/usr/include/boinc/app_ipc.h
/usr/include/boinc/average.h
/usr/include/boinc/base64.h
/usr/include/boinc/boinc_api.h
/usr/include/boinc/boinc_fcgi.h
/usr/include/boinc/boinc_opencl.h
/usr/include/boinc/cal_boinc.h
/usr/include/boinc/cc_config.h
/usr/include/boinc/cert_sig.h
/usr/include/boinc/cl_boinc.h
/usr/include/boinc/common_defs.h
/usr/include/boinc/coproc.h
/usr/include/boinc/crypt.h
/usr/include/boinc/diagnostics.h
/usr/include/boinc/error_numbers.h
/usr/include/boinc/filesys.h
/usr/include/boinc/graphics2.h
/usr/include/boinc/gui_rpc_client.h
/usr/include/boinc/gutil.h
/usr/include/boinc/hostinfo.h
/usr/include/boinc/md5.h
/usr/include/boinc/md5_file.h
/usr/include/boinc/mem_usage.h
/usr/include/boinc/mfile.h
/usr/include/boinc/miofile.h
/usr/include/boinc/msg_log.h
/usr/include/boinc/network.h
/usr/include/boinc/notice.h
/usr/include/boinc/opencl_boinc.h
/usr/include/boinc/parse.h
/usr/include/boinc/prefs.h
/usr/include/boinc/procinfo.h
/usr/include/boinc/proxy_info.h
/usr/include/boinc/sched_msgs.h
/usr/include/boinc/stackwalker_imports.h
/usr/include/boinc/str_util.h
/usr/include/boinc/svn_version.h
/usr/include/boinc/url.h
/usr/include/boinc/util.h
/usr/include/boinc/version.h
/usr/lib64/libboinc_api.so
/usr/lib64/libboinc_opencl.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libboinc_api.so.7
/usr/lib64/libboinc_api.so.7.14.2
/usr/lib64/libboinc_opencl.so.7
/usr/lib64/libboinc_opencl.so.7.14.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/boinc-client/COPYING
/usr/share/package-licenses/boinc-client/COPYING.LESSER
/usr/share/package-licenses/boinc-client/api_ttf_liberation-fonts-ttf-2.00.0_LICENSE
/usr/share/package-licenses/boinc-client/drupal_sites_all_libraries_phpmailer_LICENSE
/usr/share/package-licenses/boinc-client/drupal_sites_all_libraries_tinymce_jscripts_tiny_mce_license.txt
/usr/share/package-licenses/boinc-client/drupal_sites_all_themes_zen_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_bbcode_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_cck_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_content_profile_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_elysia_cron_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_features_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_filefield_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_flag_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_forum_access_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_htmlpurifier_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_i18nviews_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_jump_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_panels_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_privatemsg_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_views_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_contrib_wysiwyg_LICENSE.txt
/usr/share/package-licenses/boinc-client/drupal_sites_default_boinc_modules_node_comment_block_LICENSE.txt
/usr/share/package-licenses/boinc-client/html_inc_random_compat_LICENSE
/usr/share/package-licenses/boinc-client/samples_wrappture_license.terms

%files services
%defattr(-,root,root,-)
/usr/lib/systemd/system/boinc-client.service

%files locales -f BOINC-Client.lang -f BOINC-Manager.lang
%defattr(-,root,root,-)

